CREATE TYPE window_type AS ENUM (
    'MAIN_KEYBOARD',
    'BACK_KEYBOARD',
    'CHOOSE_KEYBOARD',
    'CANCEL_KEYBOARD',
    'FIX_KEYBOARD'
);

CREATE TYPE stage_type AS ENUM (
    'NONE',
    'WAITING_FOR_DATE',
    'WAITING_FOR_TIME',
    'WAITING_FOR_NAME',
    'WAITING_FOR_DESCRIPTION',
    'WAITING_FOR_DELETE_ALL',
    'WAITING_FOR_DELETE_EVENT',
    'WAITING_FOR_DELETE_NOTICE_NUMBER',
    'WAITING_FOR_DELETE_NOTICE',
    'WAITING_FOR_EVENT',
    'WAITING_FOR_DATE_NOTICE_CHOOSE',
    'WAITING_FOR_TIME_NOTICE_CHOOSE',
    'WAITING_FOR_FIX_DATE',
    'WAITING_FOR_FIX_TIME',
    'WAITING_FOR_FIX_NAME',
    'WAITING_FOR_FIX_DESCRIPTION',
    'WAITING_FOR_TIME_ZONE',
    'WAITING_FOR_DELETE_NOTICE_CHOOSE',
    'BACK'
);

CREATE TABLE tg_event.UserState (
    UserID TEXT UNIQUE,
    WindowTG window_type NOT NULL,
    Stage stage_type NOT NULL,
    NoticeID INTEGER NULL,
    EventID INTEGER NULL,

    FOREIGN KEY (UserID) REFERENCES tg_event.User(TgID) ON DELETE CASCADE,
    FOREIGN KEY (NoticeID) REFERENCES tg_event.Notice(NoticeID) ON DELETE SET NULL,
    FOREIGN KEY (EventID) REFERENCES tg_event.Event(EventID) ON DELETE SET NULL
);